server:
  port: 8080
  environment: production
  read_timeout: 10s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  database: ${DB_DATABASE}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  max_idle_conns: 25
  max_open_conns: 100
  conn_max_lifetime: 300s

auth:
  jwt_secret: ${JWT_SECRET}
  bcrypt_cost: 14
  access_token_ttl: 15m
  refresh_token_ttl: 168h
  csrf_secret: ${CSRF_SECRET}

logging:
  level: info
  environment: production

finance:
  healthy_dti_ratio: 0.36
  min_savings_rate: 0.20
  emergency_fund_months: 6